# Generated by Django 5.1 on 2026-02-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quiz_id",
                    models.CharField(max_length=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "I gang"), ("completed", "Fuldført")],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("state_json", models.JSONField(default=dict)),
                ("raw_state_payload", models.TextField(blank=True, null=True)),
                ("answers_count", models.PositiveIntegerField(default=0)),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("last_view", models.CharField(default="question", max_length=32)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "status"], name="quiz_prog_user_status_idx"),
                    models.Index(fields=["quiz_id"], name="quiz_prog_quiz_id_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="quizprogress",
            constraint=models.UniqueConstraint(fields=("user", "quiz_id"), name="uq_user_quiz_progress"),
        ),
    ]
