# Generated by Django 5.2.11 on 2026-02-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_userpreference_subjectenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyGamificationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('answered_delta', models.PositiveIntegerField(default=0)),
                ('completed_delta', models.PositiveIntegerField(default=0)),
                ('goal_target', models.PositiveIntegerField(default=20)),
                ('goal_met', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='daily_stat_user_date_idx'), models.Index(fields=['user', 'goal_met'], name='daily_stat_user_goal_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uq_user_gamification_day')],
            },
        ),
        migrations.CreateModel(
            name='UserExtensionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(choices=[('habitica', 'Habitica'), ('anki', 'Anki')], max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('enabled_by', models.CharField(blank=True, max_length=150)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('idle', 'Idle'), ('ok', 'OK'), ('error', 'Error')], default='idle', max_length=16)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_sync_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'enabled'], name='ext_access_user_enabled_idx'), models.Index(fields=['extension', 'enabled'], name='ext_access_ext_enabled_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'extension'), name='uq_user_extension_access')],
            },
        ),
        migrations.CreateModel(
            name='UserExtensionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='ext_token_user_revoked_idx'), models.Index(fields=['token_prefix'], name='ext_token_prefix_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserUnitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.CharField(max_length=64)),
                ('unit_key', models.CharField(max_length=32)),
                ('unit_label', models.CharField(max_length=128)),
                ('sequence_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('locked', 'Låst'), ('active', 'Aktiv'), ('completed', 'Fuldført')], default='locked', max_length=16)),
                ('completed_quizzes', models.PositiveIntegerField(default=0)),
                ('total_quizzes', models.PositiveIntegerField(default=0)),
                ('mastery_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_slug'], name='unit_prog_user_subject_idx'), models.Index(fields=['user', 'status'], name='unit_prog_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'subject_slug', 'unit_key'), name='uq_user_subject_unit')],
            },
        ),
    ]
