# Generated by Django 5.2.11 on 2026-02-22 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_usergamificationprofile_dailygamificationstat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionSyncLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(choices=[('habitica', 'Habitica'), ('anki', 'Anki')], max_length=16)),
                ('sync_date', models.DateField()),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('skipped', 'Skipped')], max_length=16)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtensionCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(choices=[('habitica', 'Habitica'), ('anki', 'Anki')], max_length=16)),
                ('encrypted_payload', models.TextField()),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserExtensionToken',
        ),
        migrations.AddIndex(
            model_name='extensionsyncledger',
            index=models.Index(fields=['extension', 'sync_date'], name='ext_ledger_ext_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='extensionsyncledger',
            constraint=models.UniqueConstraint(fields=('user', 'extension', 'sync_date'), name='uq_user_extension_sync_date'),
        ),
        migrations.AddIndex(
            model_name='userextensioncredential',
            index=models.Index(fields=['user', 'extension'], name='ext_cred_user_ext_idx'),
        ),
        migrations.AddConstraint(
            model_name='userextensioncredential',
            constraint=models.UniqueConstraint(fields=('user', 'extension'), name='uq_user_extension_credential'),
        ),
    ]
