# Generated by Django 5.2.11 on 2026-02-22 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_extensionsyncledger_userextensioncredential_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.CharField(max_length=64)),
                ('lecture_key', models.CharField(max_length=32)),
                ('lecture_title', models.CharField(max_length=255)),
                ('sequence_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('locked', 'Låst'), ('active', 'Aktiv'), ('completed', 'Fuldført')], default='locked', max_length=16)),
                ('completed_quizzes', models.PositiveIntegerField(default=0)),
                ('total_quizzes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_slug'], name='lecture_prog_user_subject_idx'), models.Index(fields=['user', 'status'], name='lecture_prog_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'subject_slug', 'lecture_key'), name='uq_user_subject_lecture')],
            },
        ),
        migrations.CreateModel(
            name='UserReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.CharField(max_length=64)),
                ('lecture_key', models.CharField(max_length=32)),
                ('reading_key', models.CharField(max_length=96)),
                ('reading_title', models.CharField(max_length=255)),
                ('sequence_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('locked', 'Låst'), ('active', 'Aktiv'), ('completed', 'Fuldført'), ('no_quiz', 'Ingen quiz')], default='locked', max_length=16)),
                ('completed_quizzes', models.PositiveIntegerField(default=0)),
                ('total_quizzes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_slug', 'lecture_key'], name='reading_prog_user_lecture_idx'), models.Index(fields=['user', 'status'], name='reading_prog_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'subject_slug', 'lecture_key', 'reading_key'), name='uq_user_subject_lecture_reading')],
            },
        ),
    ]
