# Generated by Django 5.2.11 on 2026-02-25 20:33

from django.db import migrations, models


def _migrate_locked_to_active(apps, schema_editor):
    user_unit_progress = apps.get_model("quizzes", "UserUnitProgress")
    user_lecture_progress = apps.get_model("quizzes", "UserLectureProgress")
    user_reading_progress = apps.get_model("quizzes", "UserReadingProgress")
    user_unit_progress.objects.filter(status="locked").update(status="active")
    user_lecture_progress.objects.filter(status="locked").update(status="active")
    user_reading_progress.objects.filter(status="locked").update(status="active")


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_userlectureprogress_userreadingprogress'),
    ]

    operations = [
        migrations.RunPython(_migrate_locked_to_active, _noop_reverse),
        migrations.AlterField(
            model_name='userlectureprogress',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Fuldført')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='userreadingprogress',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Fuldført'), ('no_quiz', 'Ingen quiz')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='userunitprogress',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Fuldført')], default='active', max_length=16),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
