# Generated by Django 5.2.11 on 2026-02-26 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_userinterfacepreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeaderboardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_alias', models.CharField(blank=True, max_length=24, null=True)),
                ('public_alias_normalized', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_public', 'public_alias_normalized'], name='leader_public_alias_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPodcastMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.CharField(max_length=64)),
                ('lecture_key', models.CharField(max_length=32)),
                ('reading_key', models.CharField(blank=True, max_length=96, null=True)),
                ('podcast_key', models.CharField(max_length=40)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_slug'], name='podcast_mark_user_subject_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reading_key__isnull', False)), fields=('user', 'subject_slug', 'lecture_key', 'reading_key', 'podcast_key'), name='uq_user_subject_lecture_reading_podcast_mark'), models.UniqueConstraint(condition=models.Q(('reading_key__isnull', True)), fields=('user', 'subject_slug', 'lecture_key', 'podcast_key'), name='uq_user_subject_lecture_podcast_mark')],
            },
        ),
        migrations.CreateModel(
            name='UserReadingMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.CharField(max_length=64)),
                ('lecture_key', models.CharField(max_length=32)),
                ('reading_key', models.CharField(max_length=96)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_slug'], name='reading_mark_user_subject_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'subject_slug', 'lecture_key', 'reading_key'), name='uq_user_subject_lecture_reading_mark')],
            },
        ),
    ]
