# Generated by Django 5.2.11 on 2026-02-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_userleaderboardprofile_userpodcastmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='attempt_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='last_attempt_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='leaderboard_best_correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='leaderboard_best_duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='leaderboard_best_question_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='leaderboard_best_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='leaderboard_best_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='leaderboard_season_key',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='retry_cooldown_until_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='retry_streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
