# Generated by Django 5.2.11 on 2026-02-28 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quizprogress_attempt_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubjectLastLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.CharField(max_length=64)),
                ('lecture_key', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_slug'], name='subject_last_user_slug_idx'), models.Index(fields=['subject_slug'], name='subject_last_slug_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'subject_slug'), name='uq_user_subject_last_lecture')],
            },
        ),
    ]
