# Generated by Django 5.2.11 on 2026-04-16 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _disable_notifications_for_existing_users(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    user_model = apps.get_model(app_label, model_name)
    preference_model = apps.get_model("quizzes", "UserNotificationPreference")
    batch: list[object] = []
    for user_id in user_model.objects.values_list("id", flat=True).iterator(chunk_size=1000):
        batch.append(
            preference_model(
                user_id=user_id,
                activity_notifications_enabled=False,
            )
        )
        if len(batch) < 1000:
            continue
        preference_model.objects.bulk_create(batch, batch_size=1000)
        batch = []
    if batch:
        preference_model.objects.bulk_create(batch, batch_size=1000)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_rename_quizprogress_leaderboard_semester_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_notifications_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(_disable_notifications_for_existing_users, _noop_reverse),
    ]
