# Generated by Django 5.2.11 on 2026-05-19 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_flashcardreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.CharField(max_length=64)),
                ('deck_slug', models.CharField(max_length=96)),
                ('card_id', models.CharField(max_length=96)),
                ('answer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'subject_slug', 'deck_slug'], name='flash_ans_user_deck_idx'), models.Index(fields=['subject_slug', 'deck_slug', 'card_id'], name='flash_ans_card_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'subject_slug', 'deck_slug', 'card_id'), name='uq_user_flashcard_answer')],
            },
        ),
    ]
