# Generated by Django 5.2.11 on 2026-05-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_flashcarduseranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreference',
            name='announcement_emails_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='announcement_unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
