#!/usr/bin/env python3
"""Audit Personlighedspsykologi concept quiz category fit."""

from __future__ import annotations

import argparse
import json
import re
import unicodedata
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
CONCEPT_MANIFEST_PATH = REPO_ROOT / "shows/personlighedspsykologi-en/concept_quizzes/concept_quiz_manifest.json"
CONTRACTS_PATH = REPO_ROOT / "shows/personlighedspsykologi-en/concept_quizzes/category_contracts.json"
DEFAULT_REPORT_PATH = REPO_ROOT / "shows/personlighedspsykologi-en/concept_quizzes/category_fit_report.md"


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _normalize(value: str) -> str:
    text = unicodedata.normalize("NFKD", value.casefold())
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.replace("æ", "ae").replace("ø", "oe").replace("å", "aa")
    return re.sub(r"\s+", " ", text)


def _text_blob(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return "\n".join(_text_blob(item) for item in value)
    if isinstance(value, dict):
        return "\n".join(_text_blob(item) for item in value.values())
    return ""


def _term_hit(text: str, terms: list[str]) -> bool:
    normalized = _normalize(text)
    return any(_normalize(term) in normalized for term in terms)


def _entry_by_slug(entries: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {str(entry.get("slug") or ""): entry for entry in entries if isinstance(entry, dict)}


def _contracts_by_slug(contracts: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {str(contract.get("slug") or ""): contract for contract in contracts if isinstance(contract, dict)}


def _correct_answer_text(question: dict[str, Any]) -> str:
    answers = question.get("answerOptions")
    if not isinstance(answers, list):
        return ""
    return " / ".join(
        str(answer.get("text") or "")
        for answer in answers
        if isinstance(answer, dict) and answer.get("isCorrect") is True
    )


def audit() -> tuple[list[str], str]:
    manifest = _load_json(CONCEPT_MANIFEST_PATH)
    contracts_payload = _load_json(CONTRACTS_PATH)
    entries = manifest.get("entries") if isinstance(manifest, dict) else []
    contracts = contracts_payload.get("contracts") if isinstance(contracts_payload, dict) else []
    if not isinstance(entries, list):
        raise SystemExit(f"Invalid concept quiz manifest: {CONCEPT_MANIFEST_PATH}")
    if not isinstance(contracts, list):
        raise SystemExit(f"Invalid category contracts file: {CONTRACTS_PATH}")

    entries_by_slug = _entry_by_slug(entries)
    contracts_by_slug = _contracts_by_slug(contracts)
    errors: list[str] = []
    lines: list[str] = [
        "# Personlighedspsykologi Concept Quiz Category Fit Report",
        "",
        "Generated by `scripts/audit_personlighedspsykologi_concept_quiz_categories.py`.",
        "",
    ]

    missing_contracts = sorted(set(entries_by_slug) - set(contracts_by_slug))
    missing_entries = sorted(set(contracts_by_slug) - set(entries_by_slug))
    for slug in missing_contracts:
        errors.append(f"Missing category contract for live quiz slug: {slug}")
    for slug in missing_entries:
        errors.append(f"Category contract has no live quiz entry: {slug}")

    for slug in sorted(set(entries_by_slug) & set(contracts_by_slug)):
        entry = entries_by_slug[slug]
        contract = contracts_by_slug[slug]
        expected_title = str(contract.get("title") or "").strip()
        manifest_title = str(entry.get("title") or "").strip()
        quiz_path = REPO_ROOT / str(entry.get("repo_quiz_path") or "")
        quiz = _load_json(quiz_path)
        quiz_title = str(quiz.get("title") or "").strip() if isinstance(quiz, dict) else ""
        questions = quiz.get("questions") if isinstance(quiz, dict) else []
        if not isinstance(questions, list):
            questions = []

        title_errors: list[str] = []
        if manifest_title != expected_title:
            title_errors.append(f"manifest title is {manifest_title!r}, expected {expected_title!r}")
        if quiz_title != expected_title:
            title_errors.append(f"quiz title is {quiz_title!r}, expected {expected_title!r}")
        for title_error in title_errors:
            errors.append(f"{slug}: {title_error}")

        quiz_blob = _text_blob(quiz)
        must_cover = contract.get("must_cover")
        if not isinstance(must_cover, list):
            must_cover = []
        covered: list[str] = []
        missing: list[str] = []
        for item in must_cover:
            if not isinstance(item, dict):
                continue
            label = str(item.get("label") or item.get("id") or "").strip()
            terms = item.get("terms")
            if not isinstance(terms, list):
                terms = [label]
            term_list = [str(term) for term in terms if str(term).strip()]
            if _term_hit(quiz_blob, term_list):
                covered.append(label)
            else:
                missing.append(label)
        if missing:
            errors.append(f"{slug}: missing must-cover concept(s): {', '.join(missing)}")

        lines.extend(
            [
                f"## {expected_title}",
                "",
                f"- Slug: `{slug}`",
                f"- Quiz id: `{entry.get('quiz_id')}`",
                f"- Questions: {len(questions)}",
                f"- Title status: {'OK' if not title_errors else '; '.join(title_errors)}",
                f"- Must-cover: {len(covered)}/{len(covered) + len(missing)} covered",
            ]
        )
        if missing:
            lines.append(f"- Missing: {', '.join(missing)}")
        lines.append("")
        lines.append("| # | Question | Correct answer |")
        lines.append("|---|---|---|")
        for index, question in enumerate(questions, 1):
            if not isinstance(question, dict):
                continue
            q_text = str(question.get("question") or "").replace("|", "\\|")
            answer_text = _correct_answer_text(question).replace("|", "\\|")
            lines.append(f"| {index} | {q_text} | {answer_text} |")
        lines.append("")

    return errors, "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-report", action="store_true")
    parser.add_argument("--report-path", type=Path, default=DEFAULT_REPORT_PATH)
    args = parser.parse_args()

    errors, report = audit()
    if args.write_report:
        report_path = args.report_path
        if not report_path.is_absolute():
            report_path = (REPO_ROOT / report_path).resolve()
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(report, encoding="utf-8")
    else:
        print(report)

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
